source 'https://github.com/CocoaPods/Specs.git'
target 'equipapp' do
  pod 'AppCenter'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FontAwesome.swift'
  pod 'youtube-ios-player-helper', '0.1.4'
end
